// Contract addresses configuration
// Auto-generated by quickDeploy.ts

export interface ContractAddresses {
  factory: `0x${string}`;
  router: `0x${string}`;
  weth: `0x${string}`;
}

// Default addresses for different networks
export const CONTRACT_ADDRESSES: Record<number, ContractAddresses> = {
  // Localhost (Anvil)
  31337: {
    factory: '0x8A791620dd6260079BF849Dc5567aDC3F2FdC318' as `0x${string}`,
    router: '0x610178dA211FEF7D417bC0e6FeD39F05609AD788' as `0x${string}`,
    weth: '0x2279B7A0a67DB372996a5FaB50D91eAA73d2eBe6' as `0x${string}`,
  },
  // Add other networks as needed
};

export function getContractAddresses(chainId: number): ContractAddresses | null {
  const addresses = CONTRACT_ADDRESSES[chainId];
  if (!addresses) {
    console.warn(`Unsupported chain ID: ${chainId}`);
    return null;
  }
  
  return addresses;
}
