// Contract addresses configuration
// Auto-generated by quickDeploy.ts

export interface ContractAddresses {
  factory: `0x${string}`;
  router: `0x${string}`;
  weth: `0x${string}`;
}

// Default addresses for different networks
export const CONTRACT_ADDRESSES: Record<number, ContractAddresses> = {
  // Localhost (Anvil)
  31337: {
    factory: '0xe7f1725E7734CE288F8367e1Bb143E90bb3F0512' as `0x${string}`,
    router: '0x9fE46736679d2D9a65F0992F2272dE9f3c7fa6e0' as `0x${string}`,
    weth: '0x5FbDB2315678afecb367f032d93F642f64180aa3' as `0x${string}`,
  },
  // Add other networks as needed
};

export function getContractAddresses(chainId: number): ContractAddresses | null {
  const addresses = CONTRACT_ADDRESSES[chainId];
  if (!addresses) {
    console.warn(`Unsupported chain ID: ${chainId}`);
    return null;
  }
  
  return addresses;
}
